### ISSUE TITLE
Vocable vs. Vocabulary

### ISSUE THREAD

**Issue by l1ghty** [ScriptRaccoon/vocable-trainer-typescript#1]
wuerde nicht sagen das es hier um leben und tot geht.
habe aber trotzdem das beduerfnis diesen irrtum anzusprechen.
https://dictionary.cambridge.org/us/dictionary/english/vocable

//ez fix. gg ;)  
export const vocables: vocable[] = [  
	{ de: "Ihh", en: "Eww" },  
	{ de: "Ach", en: "Oh" },  
	{ de: "Ach nein, ausgerechnet der!", en: "Well, well, him of all people." },  
];

danke fuers video

**Comment by ScriptRaccoon** [comment]
Stimmt. Wie heißt es denn dann? "Vocabulary" wäre ja eher die ganze Sammlung von Wörtern. Kann man da wirklich nur "Word" sagen?

**Comment by ScriptRaccoon** [comment]
Sollte mit https://github.com/ScriptRaccoon/vocabulary-trainer-typescript/commit/04e33f7ef92660cbcc0a5f2f701309b7ecd64020 erledigt sein. Außerdem wurde das Repository umbenannt von `vocable-trainer-typescript` to `vocabulary-trainer-typescript`.
